title: Default

columns:
  - width: 2/3
    sections:
      fields:
        type: fields
        fields:
          headline:
            type: text
            help: Default headline is “title”.
          intro:
            type: textarea
            buttons: false
            font: monospace
          text:
            type: textarea
            font: monospace
  - width: 1/3
    sections:
      pages:
        type: pages
        info: "{{ page.intendedTemplate }}"
      files:
        type: files
