title: Default

columns:
  - width: 2/3
    sections:
      fields:
        type: fields
        fields:
          headline:
            type: text
            help: Default headline is “title”.
          shortDescription:
            type: textarea
            buttons: false
          text:
            type: textarea
          redirect:
            type: toggle
      sections:
        headline: Sections
        type: fields
        fields:
          sections:
            type: blocks
            pretty: true
            fieldsets:
              - section
  - width: 1/3
    sections:
      pages:
        type: pages
        info: "{{ page.intendedTemplate }}"
      files:
        type: files
